# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .connection import *
from .databricks_credential import *
from .environment import *
from .environment_variable import *
from .get_connection import *
from .get_environment import *
from .get_environment_variable import *
from .get_group import *
from .get_job import *
from .get_project import *
from .get_repository import *
from .get_snowflake_credential import *
from .get_user import *
from .group import *
from .job import *
from .project import *
from .project_connection import *
from .project_repository import *
from .provider import *
from .repository import *
from .snowflake_credential import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_dbtcloud.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_dbtcloud.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "dbtcloud",
  "mod": "index/connection",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/connection:Connection": "Connection"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/databricksCredential",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/databricksCredential:DatabricksCredential": "DatabricksCredential"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/environment",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/environment:Environment": "Environment"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/environmentVariable",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/environmentVariable:EnvironmentVariable": "EnvironmentVariable"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/group",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/group:Group": "Group"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/job",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/job:Job": "Job"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/project",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/project:Project": "Project"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/projectConnection",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/projectConnection:ProjectConnection": "ProjectConnection"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/projectRepository",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/projectRepository:ProjectRepository": "ProjectRepository"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/repository",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/repository:Repository": "Repository"
  }
 },
 {
  "pkg": "dbtcloud",
  "mod": "index/snowflakeCredential",
  "fqn": "pulumi_dbtcloud",
  "classes": {
   "dbtcloud:index/snowflakeCredential:SnowflakeCredential": "SnowflakeCredential"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "dbtcloud",
  "token": "pulumi:providers:dbtcloud",
  "fqn": "pulumi_dbtcloud",
  "class": "Provider"
 }
]
"""
)
