# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['DatabricksCredentialArgs', 'DatabricksCredential']

@pulumi.input_type
class DatabricksCredentialArgs:
    def __init__(__self__, *,
                 adapter_id: pulumi.Input[int],
                 num_threads: pulumi.Input[int],
                 project_id: pulumi.Input[int],
                 target_name: pulumi.Input[str],
                 token: pulumi.Input[str]):
        """
        The set of arguments for constructing a DatabricksCredential resource.
        :param pulumi.Input[int] adapter_id: Databricks adapter ID for the credential
        :param pulumi.Input[int] num_threads: Number of threads to use
        :param pulumi.Input[int] project_id: Project ID to create the Databricks credential in
        :param pulumi.Input[str] target_name: Target name
        :param pulumi.Input[str] token: Token for Databricks user
        """
        pulumi.set(__self__, "adapter_id", adapter_id)
        pulumi.set(__self__, "num_threads", num_threads)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "target_name", target_name)
        pulumi.set(__self__, "token", token)

    @property
    @pulumi.getter(name="adapterId")
    def adapter_id(self) -> pulumi.Input[int]:
        """
        Databricks adapter ID for the credential
        """
        return pulumi.get(self, "adapter_id")

    @adapter_id.setter
    def adapter_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "adapter_id", value)

    @property
    @pulumi.getter(name="numThreads")
    def num_threads(self) -> pulumi.Input[int]:
        """
        Number of threads to use
        """
        return pulumi.get(self, "num_threads")

    @num_threads.setter
    def num_threads(self, value: pulumi.Input[int]):
        pulumi.set(self, "num_threads", value)

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[int]:
        """
        Project ID to create the Databricks credential in
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "project_id", value)

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Input[str]:
        """
        Target name
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "target_name", value)

    @property
    @pulumi.getter
    def token(self) -> pulumi.Input[str]:
        """
        Token for Databricks user
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[str]):
        pulumi.set(self, "token", value)


@pulumi.input_type
class _DatabricksCredentialState:
    def __init__(__self__, *,
                 adapter_id: Optional[pulumi.Input[int]] = None,
                 credential_id: Optional[pulumi.Input[int]] = None,
                 num_threads: Optional[pulumi.Input[int]] = None,
                 project_id: Optional[pulumi.Input[int]] = None,
                 target_name: Optional[pulumi.Input[str]] = None,
                 token: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering DatabricksCredential resources.
        :param pulumi.Input[int] adapter_id: Databricks adapter ID for the credential
        :param pulumi.Input[int] credential_id: The system Databricks credential ID
        :param pulumi.Input[int] num_threads: Number of threads to use
        :param pulumi.Input[int] project_id: Project ID to create the Databricks credential in
        :param pulumi.Input[str] target_name: Target name
        :param pulumi.Input[str] token: Token for Databricks user
        """
        if adapter_id is not None:
            pulumi.set(__self__, "adapter_id", adapter_id)
        if credential_id is not None:
            pulumi.set(__self__, "credential_id", credential_id)
        if num_threads is not None:
            pulumi.set(__self__, "num_threads", num_threads)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @property
    @pulumi.getter(name="adapterId")
    def adapter_id(self) -> Optional[pulumi.Input[int]]:
        """
        Databricks adapter ID for the credential
        """
        return pulumi.get(self, "adapter_id")

    @adapter_id.setter
    def adapter_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "adapter_id", value)

    @property
    @pulumi.getter(name="credentialId")
    def credential_id(self) -> Optional[pulumi.Input[int]]:
        """
        The system Databricks credential ID
        """
        return pulumi.get(self, "credential_id")

    @credential_id.setter
    def credential_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "credential_id", value)

    @property
    @pulumi.getter(name="numThreads")
    def num_threads(self) -> Optional[pulumi.Input[int]]:
        """
        Number of threads to use
        """
        return pulumi.get(self, "num_threads")

    @num_threads.setter
    def num_threads(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "num_threads", value)

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[int]]:
        """
        Project ID to create the Databricks credential in
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "project_id", value)

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[str]]:
        """
        Target name
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "target_name", value)

    @property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[str]]:
        """
        Token for Databricks user
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "token", value)


class DatabricksCredential(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adapter_id: Optional[pulumi.Input[int]] = None,
                 num_threads: Optional[pulumi.Input[int]] = None,
                 project_id: Optional[pulumi.Input[int]] = None,
                 target_name: Optional[pulumi.Input[str]] = None,
                 token: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a DatabricksCredential resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] adapter_id: Databricks adapter ID for the credential
        :param pulumi.Input[int] num_threads: Number of threads to use
        :param pulumi.Input[int] project_id: Project ID to create the Databricks credential in
        :param pulumi.Input[str] target_name: Target name
        :param pulumi.Input[str] token: Token for Databricks user
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DatabricksCredentialArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DatabricksCredential resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DatabricksCredentialArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DatabricksCredentialArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adapter_id: Optional[pulumi.Input[int]] = None,
                 num_threads: Optional[pulumi.Input[int]] = None,
                 project_id: Optional[pulumi.Input[int]] = None,
                 target_name: Optional[pulumi.Input[str]] = None,
                 token: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DatabricksCredentialArgs.__new__(DatabricksCredentialArgs)

            if adapter_id is None and not opts.urn:
                raise TypeError("Missing required property 'adapter_id'")
            __props__.__dict__["adapter_id"] = adapter_id
            if num_threads is None and not opts.urn:
                raise TypeError("Missing required property 'num_threads'")
            __props__.__dict__["num_threads"] = num_threads
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if target_name is None and not opts.urn:
                raise TypeError("Missing required property 'target_name'")
            __props__.__dict__["target_name"] = target_name
            if token is None and not opts.urn:
                raise TypeError("Missing required property 'token'")
            __props__.__dict__["token"] = token
            __props__.__dict__["credential_id"] = None
        super(DatabricksCredential, __self__).__init__(
            'dbtcloud:index/databricksCredential:DatabricksCredential',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            adapter_id: Optional[pulumi.Input[int]] = None,
            credential_id: Optional[pulumi.Input[int]] = None,
            num_threads: Optional[pulumi.Input[int]] = None,
            project_id: Optional[pulumi.Input[int]] = None,
            target_name: Optional[pulumi.Input[str]] = None,
            token: Optional[pulumi.Input[str]] = None) -> 'DatabricksCredential':
        """
        Get an existing DatabricksCredential resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] adapter_id: Databricks adapter ID for the credential
        :param pulumi.Input[int] credential_id: The system Databricks credential ID
        :param pulumi.Input[int] num_threads: Number of threads to use
        :param pulumi.Input[int] project_id: Project ID to create the Databricks credential in
        :param pulumi.Input[str] target_name: Target name
        :param pulumi.Input[str] token: Token for Databricks user
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DatabricksCredentialState.__new__(_DatabricksCredentialState)

        __props__.__dict__["adapter_id"] = adapter_id
        __props__.__dict__["credential_id"] = credential_id
        __props__.__dict__["num_threads"] = num_threads
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["target_name"] = target_name
        __props__.__dict__["token"] = token
        return DatabricksCredential(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="adapterId")
    def adapter_id(self) -> pulumi.Output[int]:
        """
        Databricks adapter ID for the credential
        """
        return pulumi.get(self, "adapter_id")

    @property
    @pulumi.getter(name="credentialId")
    def credential_id(self) -> pulumi.Output[int]:
        """
        The system Databricks credential ID
        """
        return pulumi.get(self, "credential_id")

    @property
    @pulumi.getter(name="numThreads")
    def num_threads(self) -> pulumi.Output[int]:
        """
        Number of threads to use
        """
        return pulumi.get(self, "num_threads")

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[int]:
        """
        Project ID to create the Databricks credential in
        """
        return pulumi.get(self, "project_id")

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Output[str]:
        """
        Target name
        """
        return pulumi.get(self, "target_name")

    @property
    @pulumi.getter
    def token(self) -> pulumi.Output[str]:
        """
        Token for Databricks user
        """
        return pulumi.get(self, "token")

