// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dbtcloud
{
    public static class GetEnvironmentVariable
    {
        public static Task<GetEnvironmentVariableResult> InvokeAsync(GetEnvironmentVariableArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentVariableResult>("dbtcloud:index/getEnvironmentVariable:getEnvironmentVariable", args ?? new GetEnvironmentVariableArgs(), options.WithDefaults());

        public static Output<GetEnvironmentVariableResult> Invoke(GetEnvironmentVariableInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetEnvironmentVariableResult>("dbtcloud:index/getEnvironmentVariable:getEnvironmentVariable", args ?? new GetEnvironmentVariableInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentVariableArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public GetEnvironmentVariableArgs()
        {
        }
        public static new GetEnvironmentVariableArgs Empty => new GetEnvironmentVariableArgs();
    }

    public sealed class GetEnvironmentVariableInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public GetEnvironmentVariableInvokeArgs()
        {
        }
        public static new GetEnvironmentVariableInvokeArgs Empty => new GetEnvironmentVariableInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentVariableResult
    {
        public readonly ImmutableDictionary<string, object> EnvironmentValues;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int ProjectId;

        [OutputConstructor]
        private GetEnvironmentVariableResult(
            ImmutableDictionary<string, object> environmentValues,

            string id,

            string name,

            int projectId)
        {
            EnvironmentValues = environmentValues;
            Id = id;
            Name = name;
            ProjectId = projectId;
        }
    }
}
