// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dbtcloud
{
    public static class GetEnvironment
    {
        public static Task<GetEnvironmentResult> InvokeAsync(GetEnvironmentArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentResult>("dbtcloud:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentArgs(), options.WithDefaults());

        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("dbtcloud:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        [Input("environmentId", required: true)]
        public int EnvironmentId { get; set; }

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public GetEnvironmentArgs()
        {
        }
        public static new GetEnvironmentArgs Empty => new GetEnvironmentArgs();
    }

    public sealed class GetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("environmentId", required: true)]
        public Input<int> EnvironmentId { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public GetEnvironmentInvokeArgs()
        {
        }
        public static new GetEnvironmentInvokeArgs Empty => new GetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentResult
    {
        public readonly int CredentialId;
        public readonly string CustomBranch;
        public readonly string DbtVersion;
        public readonly int EnvironmentId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsActive;
        public readonly string Name;
        public readonly int ProjectId;
        public readonly string Type;
        public readonly bool UseCustomBranch;

        [OutputConstructor]
        private GetEnvironmentResult(
            int credentialId,

            string customBranch,

            string dbtVersion,

            int environmentId,

            string id,

            bool isActive,

            string name,

            int projectId,

            string type,

            bool useCustomBranch)
        {
            CredentialId = credentialId;
            CustomBranch = customBranch;
            DbtVersion = dbtVersion;
            EnvironmentId = environmentId;
            Id = id;
            IsActive = isActive;
            Name = name;
            ProjectId = projectId;
            Type = type;
            UseCustomBranch = useCustomBranch;
        }
    }
}
