// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dbtcloud
{
    public static class GetJob
    {
        public static Task<GetJobResult> InvokeAsync(GetJobArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetJobResult>("dbtcloud:index/getJob:getJob", args ?? new GetJobArgs(), options.WithDefaults());

        public static Output<GetJobResult> Invoke(GetJobInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetJobResult>("dbtcloud:index/getJob:getJob", args ?? new GetJobInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetJobArgs : global::Pulumi.InvokeArgs
    {
        [Input("jobId", required: true)]
        public int JobId { get; set; }

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public GetJobArgs()
        {
        }
        public static new GetJobArgs Empty => new GetJobArgs();
    }

    public sealed class GetJobInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("jobId", required: true)]
        public Input<int> JobId { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public GetJobInvokeArgs()
        {
        }
        public static new GetJobInvokeArgs Empty => new GetJobInvokeArgs();
    }


    [OutputType]
    public sealed class GetJobResult
    {
        public readonly int DeferringJobId;
        public readonly int EnvironmentId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int JobId;
        public readonly string Name;
        public readonly int ProjectId;
        public readonly bool SelfDeferring;
        public readonly int TimeoutSeconds;
        public readonly ImmutableDictionary<string, bool> Triggers;

        [OutputConstructor]
        private GetJobResult(
            int deferringJobId,

            int environmentId,

            string id,

            int jobId,

            string name,

            int projectId,

            bool selfDeferring,

            int timeoutSeconds,

            ImmutableDictionary<string, bool> triggers)
        {
            DeferringJobId = deferringJobId;
            EnvironmentId = environmentId;
            Id = id;
            JobId = jobId;
            Name = name;
            ProjectId = projectId;
            SelfDeferring = selfDeferring;
            TimeoutSeconds = timeoutSeconds;
            Triggers = triggers;
        }
    }
}
