// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dbtcloud
{
    public static class GetRepository
    {
        public static Task<GetRepositoryResult> InvokeAsync(GetRepositoryArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetRepositoryResult>("dbtcloud:index/getRepository:getRepository", args ?? new GetRepositoryArgs(), options.WithDefaults());

        public static Output<GetRepositoryResult> Invoke(GetRepositoryInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetRepositoryResult>("dbtcloud:index/getRepository:getRepository", args ?? new GetRepositoryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRepositoryArgs : global::Pulumi.InvokeArgs
    {
        [Input("fetchDeployKey")]
        public bool? FetchDeployKey { get; set; }

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        [Input("repositoryId", required: true)]
        public int RepositoryId { get; set; }

        public GetRepositoryArgs()
        {
        }
        public static new GetRepositoryArgs Empty => new GetRepositoryArgs();
    }

    public sealed class GetRepositoryInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("fetchDeployKey")]
        public Input<bool>? FetchDeployKey { get; set; }

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        [Input("repositoryId", required: true)]
        public Input<int> RepositoryId { get; set; } = null!;

        public GetRepositoryInvokeArgs()
        {
        }
        public static new GetRepositoryInvokeArgs Empty => new GetRepositoryInvokeArgs();
    }


    [OutputType]
    public sealed class GetRepositoryResult
    {
        public readonly string DeployKey;
        public readonly bool? FetchDeployKey;
        public readonly string GitCloneStrategy;
        public readonly int GitlabProjectId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsActive;
        public readonly int ProjectId;
        public readonly string RemoteUrl;
        public readonly int RepositoryCredentialsId;
        public readonly int RepositoryId;

        [OutputConstructor]
        private GetRepositoryResult(
            string deployKey,

            bool? fetchDeployKey,

            string gitCloneStrategy,

            int gitlabProjectId,

            string id,

            bool isActive,

            int projectId,

            string remoteUrl,

            int repositoryCredentialsId,

            int repositoryId)
        {
            DeployKey = deployKey;
            FetchDeployKey = fetchDeployKey;
            GitCloneStrategy = gitCloneStrategy;
            GitlabProjectId = gitlabProjectId;
            Id = id;
            IsActive = isActive;
            ProjectId = projectId;
            RemoteUrl = remoteUrl;
            RepositoryCredentialsId = repositoryCredentialsId;
            RepositoryId = repositoryId;
        }
    }
}
