// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dbtcloud
{
    public static class GetSnowflakeCredential
    {
        public static Task<GetSnowflakeCredentialResult> InvokeAsync(GetSnowflakeCredentialArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSnowflakeCredentialResult>("dbtcloud:index/getSnowflakeCredential:getSnowflakeCredential", args ?? new GetSnowflakeCredentialArgs(), options.WithDefaults());

        public static Output<GetSnowflakeCredentialResult> Invoke(GetSnowflakeCredentialInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSnowflakeCredentialResult>("dbtcloud:index/getSnowflakeCredential:getSnowflakeCredential", args ?? new GetSnowflakeCredentialInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSnowflakeCredentialArgs : global::Pulumi.InvokeArgs
    {
        [Input("credentialId", required: true)]
        public int CredentialId { get; set; }

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public GetSnowflakeCredentialArgs()
        {
        }
        public static new GetSnowflakeCredentialArgs Empty => new GetSnowflakeCredentialArgs();
    }

    public sealed class GetSnowflakeCredentialInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("credentialId", required: true)]
        public Input<int> CredentialId { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public GetSnowflakeCredentialInvokeArgs()
        {
        }
        public static new GetSnowflakeCredentialInvokeArgs Empty => new GetSnowflakeCredentialInvokeArgs();
    }


    [OutputType]
    public sealed class GetSnowflakeCredentialResult
    {
        public readonly string AuthType;
        public readonly int CredentialId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsActive;
        public readonly int NumThreads;
        public readonly int ProjectId;
        public readonly string Schema;
        public readonly string User;

        [OutputConstructor]
        private GetSnowflakeCredentialResult(
            string authType,

            int credentialId,

            string id,

            bool isActive,

            int numThreads,

            int projectId,

            string schema,

            string user)
        {
            AuthType = authType;
            CredentialId = credentialId;
            Id = id;
            IsActive = isActive;
            NumThreads = numThreads;
            ProjectId = projectId;
            Schema = schema;
            User = user;
        }
    }
}
