// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Account identifier for your DBT Cloud implementation
func GetAccountId(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "dbtcloud:accountId")
}

// URL for your DBT Cloud deployment
func GetHostUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "dbtcloud:hostUrl")
}

// API token for your DBT Cloud
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "dbtcloud:token")
}
