// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("dbtcloud");

/**
 * Account identifier for your DBT Cloud implementation
 */
export declare const accountId: number | undefined;
Object.defineProperty(exports, "accountId", {
    get() {
        return __config.getObject<number>("accountId");
    },
    enumerable: true,
});

/**
 * URL for your DBT Cloud deployment
 */
export declare const hostUrl: string | undefined;
Object.defineProperty(exports, "hostUrl", {
    get() {
        return __config.get("hostUrl");
    },
    enumerable: true,
});

/**
 * API token for your DBT Cloud
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

