# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

accountId: Optional[int]
"""
Account identifier for your DBT Cloud implementation
"""

hostUrl: Optional[str]
"""
URL for your DBT Cloud deployment
"""

token: Optional[str]
"""
API token for your DBT Cloud
"""

