// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupConnection(ctx *pulumi.Context, args *LookupConnectionArgs, opts ...pulumi.InvokeOption) (*LookupConnectionResult, error) {
	var rv LookupConnectionResult
	err := ctx.Invoke("dbtcloud:index/getConnection:getConnection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getConnection.
type LookupConnectionArgs struct {
	ConnectionId int `pulumi:"connectionId"`
	ProjectId    int `pulumi:"projectId"`
}

// A collection of values returned by getConnection.
type LookupConnectionResult struct {
	Account        string `pulumi:"account"`
	AllowKeepAlive bool   `pulumi:"allowKeepAlive"`
	AllowSso       bool   `pulumi:"allowSso"`
	ConnectionId   int    `pulumi:"connectionId"`
	Database       string `pulumi:"database"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	IsActive  bool   `pulumi:"isActive"`
	Name      string `pulumi:"name"`
	ProjectId int    `pulumi:"projectId"`
	Role      string `pulumi:"role"`
	Type      string `pulumi:"type"`
	Warehouse string `pulumi:"warehouse"`
}

func LookupConnectionOutput(ctx *pulumi.Context, args LookupConnectionOutputArgs, opts ...pulumi.InvokeOption) LookupConnectionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupConnectionResult, error) {
			args := v.(LookupConnectionArgs)
			r, err := LookupConnection(ctx, &args, opts...)
			var s LookupConnectionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupConnectionResultOutput)
}

// A collection of arguments for invoking getConnection.
type LookupConnectionOutputArgs struct {
	ConnectionId pulumi.IntInput `pulumi:"connectionId"`
	ProjectId    pulumi.IntInput `pulumi:"projectId"`
}

func (LookupConnectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConnectionArgs)(nil)).Elem()
}

// A collection of values returned by getConnection.
type LookupConnectionResultOutput struct{ *pulumi.OutputState }

func (LookupConnectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConnectionResult)(nil)).Elem()
}

func (o LookupConnectionResultOutput) ToLookupConnectionResultOutput() LookupConnectionResultOutput {
	return o
}

func (o LookupConnectionResultOutput) ToLookupConnectionResultOutputWithContext(ctx context.Context) LookupConnectionResultOutput {
	return o
}

func (o LookupConnectionResultOutput) Account() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Account }).(pulumi.StringOutput)
}

func (o LookupConnectionResultOutput) AllowKeepAlive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupConnectionResult) bool { return v.AllowKeepAlive }).(pulumi.BoolOutput)
}

func (o LookupConnectionResultOutput) AllowSso() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupConnectionResult) bool { return v.AllowSso }).(pulumi.BoolOutput)
}

func (o LookupConnectionResultOutput) ConnectionId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupConnectionResult) int { return v.ConnectionId }).(pulumi.IntOutput)
}

func (o LookupConnectionResultOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Database }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupConnectionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupConnectionResultOutput) IsActive() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupConnectionResult) bool { return v.IsActive }).(pulumi.BoolOutput)
}

func (o LookupConnectionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupConnectionResultOutput) ProjectId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupConnectionResult) int { return v.ProjectId }).(pulumi.IntOutput)
}

func (o LookupConnectionResultOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Role }).(pulumi.StringOutput)
}

func (o LookupConnectionResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupConnectionResultOutput) Warehouse() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectionResult) string { return v.Warehouse }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupConnectionResultOutput{})
}
