// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupJob(ctx *pulumi.Context, args *LookupJobArgs, opts ...pulumi.InvokeOption) (*LookupJobResult, error) {
	var rv LookupJobResult
	err := ctx.Invoke("dbtcloud:index/getJob:getJob", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getJob.
type LookupJobArgs struct {
	JobId     int `pulumi:"jobId"`
	ProjectId int `pulumi:"projectId"`
}

// A collection of values returned by getJob.
type LookupJobResult struct {
	DeferringJobId int `pulumi:"deferringJobId"`
	EnvironmentId  int `pulumi:"environmentId"`
	// The provider-assigned unique ID for this managed resource.
	Id             string          `pulumi:"id"`
	JobId          int             `pulumi:"jobId"`
	Name           string          `pulumi:"name"`
	ProjectId      int             `pulumi:"projectId"`
	SelfDeferring  bool            `pulumi:"selfDeferring"`
	TimeoutSeconds int             `pulumi:"timeoutSeconds"`
	Triggers       map[string]bool `pulumi:"triggers"`
}

func LookupJobOutput(ctx *pulumi.Context, args LookupJobOutputArgs, opts ...pulumi.InvokeOption) LookupJobResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupJobResult, error) {
			args := v.(LookupJobArgs)
			r, err := LookupJob(ctx, &args, opts...)
			var s LookupJobResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupJobResultOutput)
}

// A collection of arguments for invoking getJob.
type LookupJobOutputArgs struct {
	JobId     pulumi.IntInput `pulumi:"jobId"`
	ProjectId pulumi.IntInput `pulumi:"projectId"`
}

func (LookupJobOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupJobArgs)(nil)).Elem()
}

// A collection of values returned by getJob.
type LookupJobResultOutput struct{ *pulumi.OutputState }

func (LookupJobResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupJobResult)(nil)).Elem()
}

func (o LookupJobResultOutput) ToLookupJobResultOutput() LookupJobResultOutput {
	return o
}

func (o LookupJobResultOutput) ToLookupJobResultOutputWithContext(ctx context.Context) LookupJobResultOutput {
	return o
}

func (o LookupJobResultOutput) DeferringJobId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupJobResult) int { return v.DeferringJobId }).(pulumi.IntOutput)
}

func (o LookupJobResultOutput) EnvironmentId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupJobResult) int { return v.EnvironmentId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupJobResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupJobResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupJobResultOutput) JobId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupJobResult) int { return v.JobId }).(pulumi.IntOutput)
}

func (o LookupJobResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupJobResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupJobResultOutput) ProjectId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupJobResult) int { return v.ProjectId }).(pulumi.IntOutput)
}

func (o LookupJobResultOutput) SelfDeferring() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupJobResult) bool { return v.SelfDeferring }).(pulumi.BoolOutput)
}

func (o LookupJobResultOutput) TimeoutSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v LookupJobResult) int { return v.TimeoutSeconds }).(pulumi.IntOutput)
}

func (o LookupJobResultOutput) Triggers() pulumi.BoolMapOutput {
	return o.ApplyT(func(v LookupJobResult) map[string]bool { return v.Triggers }).(pulumi.BoolMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupJobResultOutput{})
}
