// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "dbtcloud:index/connection:Connection":
		r = &Connection{}
	case "dbtcloud:index/databricksCredential:DatabricksCredential":
		r = &DatabricksCredential{}
	case "dbtcloud:index/environment:Environment":
		r = &Environment{}
	case "dbtcloud:index/environmentVariable:EnvironmentVariable":
		r = &EnvironmentVariable{}
	case "dbtcloud:index/group:Group":
		r = &Group{}
	case "dbtcloud:index/job:Job":
		r = &Job{}
	case "dbtcloud:index/project:Project":
		r = &Project{}
	case "dbtcloud:index/projectConnection:ProjectConnection":
		r = &ProjectConnection{}
	case "dbtcloud:index/projectRepository:ProjectRepository":
		r = &ProjectRepository{}
	case "dbtcloud:index/repository:Repository":
		r = &Repository{}
	case "dbtcloud:index/snowflakeCredential:SnowflakeCredential":
		r = &SnowflakeCredential{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:dbtcloud" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/connection",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/databricksCredential",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/environment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/environmentVariable",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/job",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/projectConnection",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/projectRepository",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/repository",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"dbtcloud",
		"index/snowflakeCredential",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"dbtcloud",
		&pkg{version},
	)
}
