// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatabricksCredential extends pulumi.CustomResource {
    /**
     * Get an existing DatabricksCredential resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabricksCredentialState, opts?: pulumi.CustomResourceOptions): DatabricksCredential {
        return new DatabricksCredential(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dbtcloud:index/databricksCredential:DatabricksCredential';

    /**
     * Returns true if the given object is an instance of DatabricksCredential.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabricksCredential {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabricksCredential.__pulumiType;
    }

    /**
     * Databricks adapter ID for the credential
     */
    public readonly adapterId!: pulumi.Output<number>;
    /**
     * The system Databricks credential ID
     */
    public /*out*/ readonly credentialId!: pulumi.Output<number>;
    /**
     * Number of threads to use
     */
    public readonly numThreads!: pulumi.Output<number>;
    /**
     * Project ID to create the Databricks credential in
     */
    public readonly projectId!: pulumi.Output<number>;
    /**
     * Target name
     */
    public readonly targetName!: pulumi.Output<string>;
    /**
     * Token for Databricks user
     */
    public readonly token!: pulumi.Output<string>;

    /**
     * Create a DatabricksCredential resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabricksCredentialArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabricksCredentialArgs | DatabricksCredentialState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabricksCredentialState | undefined;
            resourceInputs["adapterId"] = state ? state.adapterId : undefined;
            resourceInputs["credentialId"] = state ? state.credentialId : undefined;
            resourceInputs["numThreads"] = state ? state.numThreads : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["targetName"] = state ? state.targetName : undefined;
            resourceInputs["token"] = state ? state.token : undefined;
        } else {
            const args = argsOrState as DatabricksCredentialArgs | undefined;
            if ((!args || args.adapterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'adapterId'");
            }
            if ((!args || args.numThreads === undefined) && !opts.urn) {
                throw new Error("Missing required property 'numThreads'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.targetName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'targetName'");
            }
            if ((!args || args.token === undefined) && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            resourceInputs["adapterId"] = args ? args.adapterId : undefined;
            resourceInputs["numThreads"] = args ? args.numThreads : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["targetName"] = args ? args.targetName : undefined;
            resourceInputs["token"] = args ? args.token : undefined;
            resourceInputs["credentialId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatabricksCredential.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DatabricksCredential resources.
 */
export interface DatabricksCredentialState {
    /**
     * Databricks adapter ID for the credential
     */
    adapterId?: pulumi.Input<number>;
    /**
     * The system Databricks credential ID
     */
    credentialId?: pulumi.Input<number>;
    /**
     * Number of threads to use
     */
    numThreads?: pulumi.Input<number>;
    /**
     * Project ID to create the Databricks credential in
     */
    projectId?: pulumi.Input<number>;
    /**
     * Target name
     */
    targetName?: pulumi.Input<string>;
    /**
     * Token for Databricks user
     */
    token?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DatabricksCredential resource.
 */
export interface DatabricksCredentialArgs {
    /**
     * Databricks adapter ID for the credential
     */
    adapterId: pulumi.Input<number>;
    /**
     * Number of threads to use
     */
    numThreads: pulumi.Input<number>;
    /**
     * Project ID to create the Databricks credential in
     */
    projectId: pulumi.Input<number>;
    /**
     * Target name
     */
    targetName: pulumi.Input<string>;
    /**
     * Token for Databricks user
     */
    token: pulumi.Input<string>;
}
