// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getJob(args: GetJobArgs, opts?: pulumi.InvokeOptions): Promise<GetJobResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("dbtcloud:index/getJob:getJob", {
        "jobId": args.jobId,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getJob.
 */
export interface GetJobArgs {
    jobId: number;
    projectId: number;
}

/**
 * A collection of values returned by getJob.
 */
export interface GetJobResult {
    readonly deferringJobId: number;
    readonly environmentId: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly jobId: number;
    readonly name: string;
    readonly projectId: number;
    readonly selfDeferring: boolean;
    readonly timeoutSeconds: number;
    readonly triggers: {[key: string]: boolean};
}

export function getJobOutput(args: GetJobOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetJobResult> {
    return pulumi.output(args).apply(a => getJob(a, opts))
}

/**
 * A collection of arguments for invoking getJob.
 */
export interface GetJobOutputArgs {
    jobId: pulumi.Input<number>;
    projectId: pulumi.Input<number>;
}
